#!/bin/bash

# Exit immediately on non-zero return.
set -e

# Use the return value of any command that fails.
set -o pipefail

# Error on unset variables.
set -u

# Output each command before running.
set -x

# Where we get stuff.
if [ -z ${KMS_BASE_URL+x} ]; then
  KMS_BASE_URL=https://raw.githubusercontent.com/Coding-Badly/RFID-KeyMaster/006/develop/brian/pi
fi

# Where our work stuff goes.
if [ -z ${KMS_ROOT+x} ]; then
  KMS_ROOT=/home/pi/dms
fi

# Don't fail if the directory already exists.
mkdir $KMS_ROOT || true

# Create the service description.
cat > $KMS_ROOT/kms.service << EOL
[Unit]
Description=RFID-KeyMaster Setup
After=network.target

[Service]
ExecStart=/usr/bin/python3 -u kms.py
WorkingDirectory=$KMS_ROOT
StandardOutput=inherit
StandardError=inherit
#User=pi
User=root

[Install]
WantedBy=multi-user.target
EOL

# Fetch the actual code.
curl -s "$KMS_BASE_URL/kms.py" > $KMS_ROOT/kms.py

# Create and enable the kms.service.
sudo cp $KMS_ROOT/kms.service /etc/systemd/system/kms.service
sudo systemctl enable kms.service
# sudo systemctl start kms.service  # rmv

# Start it running.
# fix 
sudo reboot

